pragma circom 2.0.0;

// Lean-IMT (Incremental Merkle Tree) verification circuit
// Runtime tree_depth: only proof[0..tree_depth-1] are used; proof has fixed size 32 (max depth).
// Auto-generated unrolled circuit (Circom 2 requires components in initial scope).

include "../poseidon/poseidon.circom";
include "../../node_modules/circomlib/circuits/bitify.circom";
include "../../node_modules/circomlib/circuits/comparators.circom";

/// Verify merkle proof for lean-IMT with runtime depth
template LeanIMTVerify() {
    signal input leaf;
    signal input index;
    signal input tree_depth;
    signal input expected_root;
    signal input proof[32];

    component n2b = Num2Bits(64);
    n2b.in <== index;

    signal current[33];
    current[0] <== leaf;

    // Level 0: process only if level < tree_depth
    component lt_0 = LessThan(32);
    lt_0.in[0] <== 0;
    lt_0.in[1] <== tree_depth;
    signal should_process_0;
    should_process_0 <== lt_0.out;
    component hash_right_0 = Poseidon2Hash2();
    hash_right_0.in[0] <== proof[0];
    hash_right_0.in[1] <== current[0];
    component hash_left_0 = Poseidon2Hash2();
    hash_left_0.in[0] <== current[0];
    hash_left_0.in[1] <== proof[0];
    component sibling_zero_0 = IsZero();
    sibling_zero_0.in <== proof[0];
    signal sibling_not_zero_0;
    sibling_not_zero_0 <== 1 - sibling_zero_0.out;
    signal diff_left_0;
    diff_left_0 <== hash_left_0.out - current[0];
    signal left_case_0;
    left_case_0 <== current[0] + sibling_not_zero_0 * diff_left_0;
    signal diff_right_0;
    diff_right_0 <== hash_right_0.out - left_case_0;
    signal sel_hash_0;
    sel_hash_0 <== left_case_0 + n2b.out[0] * diff_right_0;
    signal diff_process_0;
    diff_process_0 <== sel_hash_0 - current[0];
    current[1] <== current[0] + should_process_0 * diff_process_0;

    // Level 1: process only if level < tree_depth
    component lt_1 = LessThan(32);
    lt_1.in[0] <== 1;
    lt_1.in[1] <== tree_depth;
    signal should_process_1;
    should_process_1 <== lt_1.out;
    component hash_right_1 = Poseidon2Hash2();
    hash_right_1.in[0] <== proof[1];
    hash_right_1.in[1] <== current[1];
    component hash_left_1 = Poseidon2Hash2();
    hash_left_1.in[0] <== current[1];
    hash_left_1.in[1] <== proof[1];
    component sibling_zero_1 = IsZero();
    sibling_zero_1.in <== proof[1];
    signal sibling_not_zero_1;
    sibling_not_zero_1 <== 1 - sibling_zero_1.out;
    signal diff_left_1;
    diff_left_1 <== hash_left_1.out - current[1];
    signal left_case_1;
    left_case_1 <== current[1] + sibling_not_zero_1 * diff_left_1;
    signal diff_right_1;
    diff_right_1 <== hash_right_1.out - left_case_1;
    signal sel_hash_1;
    sel_hash_1 <== left_case_1 + n2b.out[1] * diff_right_1;
    signal diff_process_1;
    diff_process_1 <== sel_hash_1 - current[1];
    current[2] <== current[1] + should_process_1 * diff_process_1;

    // Level 2: process only if level < tree_depth
    component lt_2 = LessThan(32);
    lt_2.in[0] <== 2;
    lt_2.in[1] <== tree_depth;
    signal should_process_2;
    should_process_2 <== lt_2.out;
    component hash_right_2 = Poseidon2Hash2();
    hash_right_2.in[0] <== proof[2];
    hash_right_2.in[1] <== current[2];
    component hash_left_2 = Poseidon2Hash2();
    hash_left_2.in[0] <== current[2];
    hash_left_2.in[1] <== proof[2];
    component sibling_zero_2 = IsZero();
    sibling_zero_2.in <== proof[2];
    signal sibling_not_zero_2;
    sibling_not_zero_2 <== 1 - sibling_zero_2.out;
    signal diff_left_2;
    diff_left_2 <== hash_left_2.out - current[2];
    signal left_case_2;
    left_case_2 <== current[2] + sibling_not_zero_2 * diff_left_2;
    signal diff_right_2;
    diff_right_2 <== hash_right_2.out - left_case_2;
    signal sel_hash_2;
    sel_hash_2 <== left_case_2 + n2b.out[2] * diff_right_2;
    signal diff_process_2;
    diff_process_2 <== sel_hash_2 - current[2];
    current[3] <== current[2] + should_process_2 * diff_process_2;

    // Level 3: process only if level < tree_depth
    component lt_3 = LessThan(32);
    lt_3.in[0] <== 3;
    lt_3.in[1] <== tree_depth;
    signal should_process_3;
    should_process_3 <== lt_3.out;
    component hash_right_3 = Poseidon2Hash2();
    hash_right_3.in[0] <== proof[3];
    hash_right_3.in[1] <== current[3];
    component hash_left_3 = Poseidon2Hash2();
    hash_left_3.in[0] <== current[3];
    hash_left_3.in[1] <== proof[3];
    component sibling_zero_3 = IsZero();
    sibling_zero_3.in <== proof[3];
    signal sibling_not_zero_3;
    sibling_not_zero_3 <== 1 - sibling_zero_3.out;
    signal diff_left_3;
    diff_left_3 <== hash_left_3.out - current[3];
    signal left_case_3;
    left_case_3 <== current[3] + sibling_not_zero_3 * diff_left_3;
    signal diff_right_3;
    diff_right_3 <== hash_right_3.out - left_case_3;
    signal sel_hash_3;
    sel_hash_3 <== left_case_3 + n2b.out[3] * diff_right_3;
    signal diff_process_3;
    diff_process_3 <== sel_hash_3 - current[3];
    current[4] <== current[3] + should_process_3 * diff_process_3;

    // Level 4: process only if level < tree_depth
    component lt_4 = LessThan(32);
    lt_4.in[0] <== 4;
    lt_4.in[1] <== tree_depth;
    signal should_process_4;
    should_process_4 <== lt_4.out;
    component hash_right_4 = Poseidon2Hash2();
    hash_right_4.in[0] <== proof[4];
    hash_right_4.in[1] <== current[4];
    component hash_left_4 = Poseidon2Hash2();
    hash_left_4.in[0] <== current[4];
    hash_left_4.in[1] <== proof[4];
    component sibling_zero_4 = IsZero();
    sibling_zero_4.in <== proof[4];
    signal sibling_not_zero_4;
    sibling_not_zero_4 <== 1 - sibling_zero_4.out;
    signal diff_left_4;
    diff_left_4 <== hash_left_4.out - current[4];
    signal left_case_4;
    left_case_4 <== current[4] + sibling_not_zero_4 * diff_left_4;
    signal diff_right_4;
    diff_right_4 <== hash_right_4.out - left_case_4;
    signal sel_hash_4;
    sel_hash_4 <== left_case_4 + n2b.out[4] * diff_right_4;
    signal diff_process_4;
    diff_process_4 <== sel_hash_4 - current[4];
    current[5] <== current[4] + should_process_4 * diff_process_4;

    // Level 5: process only if level < tree_depth
    component lt_5 = LessThan(32);
    lt_5.in[0] <== 5;
    lt_5.in[1] <== tree_depth;
    signal should_process_5;
    should_process_5 <== lt_5.out;
    component hash_right_5 = Poseidon2Hash2();
    hash_right_5.in[0] <== proof[5];
    hash_right_5.in[1] <== current[5];
    component hash_left_5 = Poseidon2Hash2();
    hash_left_5.in[0] <== current[5];
    hash_left_5.in[1] <== proof[5];
    component sibling_zero_5 = IsZero();
    sibling_zero_5.in <== proof[5];
    signal sibling_not_zero_5;
    sibling_not_zero_5 <== 1 - sibling_zero_5.out;
    signal diff_left_5;
    diff_left_5 <== hash_left_5.out - current[5];
    signal left_case_5;
    left_case_5 <== current[5] + sibling_not_zero_5 * diff_left_5;
    signal diff_right_5;
    diff_right_5 <== hash_right_5.out - left_case_5;
    signal sel_hash_5;
    sel_hash_5 <== left_case_5 + n2b.out[5] * diff_right_5;
    signal diff_process_5;
    diff_process_5 <== sel_hash_5 - current[5];
    current[6] <== current[5] + should_process_5 * diff_process_5;

    // Level 6: process only if level < tree_depth
    component lt_6 = LessThan(32);
    lt_6.in[0] <== 6;
    lt_6.in[1] <== tree_depth;
    signal should_process_6;
    should_process_6 <== lt_6.out;
    component hash_right_6 = Poseidon2Hash2();
    hash_right_6.in[0] <== proof[6];
    hash_right_6.in[1] <== current[6];
    component hash_left_6 = Poseidon2Hash2();
    hash_left_6.in[0] <== current[6];
    hash_left_6.in[1] <== proof[6];
    component sibling_zero_6 = IsZero();
    sibling_zero_6.in <== proof[6];
    signal sibling_not_zero_6;
    sibling_not_zero_6 <== 1 - sibling_zero_6.out;
    signal diff_left_6;
    diff_left_6 <== hash_left_6.out - current[6];
    signal left_case_6;
    left_case_6 <== current[6] + sibling_not_zero_6 * diff_left_6;
    signal diff_right_6;
    diff_right_6 <== hash_right_6.out - left_case_6;
    signal sel_hash_6;
    sel_hash_6 <== left_case_6 + n2b.out[6] * diff_right_6;
    signal diff_process_6;
    diff_process_6 <== sel_hash_6 - current[6];
    current[7] <== current[6] + should_process_6 * diff_process_6;

    // Level 7: process only if level < tree_depth
    component lt_7 = LessThan(32);
    lt_7.in[0] <== 7;
    lt_7.in[1] <== tree_depth;
    signal should_process_7;
    should_process_7 <== lt_7.out;
    component hash_right_7 = Poseidon2Hash2();
    hash_right_7.in[0] <== proof[7];
    hash_right_7.in[1] <== current[7];
    component hash_left_7 = Poseidon2Hash2();
    hash_left_7.in[0] <== current[7];
    hash_left_7.in[1] <== proof[7];
    component sibling_zero_7 = IsZero();
    sibling_zero_7.in <== proof[7];
    signal sibling_not_zero_7;
    sibling_not_zero_7 <== 1 - sibling_zero_7.out;
    signal diff_left_7;
    diff_left_7 <== hash_left_7.out - current[7];
    signal left_case_7;
    left_case_7 <== current[7] + sibling_not_zero_7 * diff_left_7;
    signal diff_right_7;
    diff_right_7 <== hash_right_7.out - left_case_7;
    signal sel_hash_7;
    sel_hash_7 <== left_case_7 + n2b.out[7] * diff_right_7;
    signal diff_process_7;
    diff_process_7 <== sel_hash_7 - current[7];
    current[8] <== current[7] + should_process_7 * diff_process_7;

    // Level 8: process only if level < tree_depth
    component lt_8 = LessThan(32);
    lt_8.in[0] <== 8;
    lt_8.in[1] <== tree_depth;
    signal should_process_8;
    should_process_8 <== lt_8.out;
    component hash_right_8 = Poseidon2Hash2();
    hash_right_8.in[0] <== proof[8];
    hash_right_8.in[1] <== current[8];
    component hash_left_8 = Poseidon2Hash2();
    hash_left_8.in[0] <== current[8];
    hash_left_8.in[1] <== proof[8];
    component sibling_zero_8 = IsZero();
    sibling_zero_8.in <== proof[8];
    signal sibling_not_zero_8;
    sibling_not_zero_8 <== 1 - sibling_zero_8.out;
    signal diff_left_8;
    diff_left_8 <== hash_left_8.out - current[8];
    signal left_case_8;
    left_case_8 <== current[8] + sibling_not_zero_8 * diff_left_8;
    signal diff_right_8;
    diff_right_8 <== hash_right_8.out - left_case_8;
    signal sel_hash_8;
    sel_hash_8 <== left_case_8 + n2b.out[8] * diff_right_8;
    signal diff_process_8;
    diff_process_8 <== sel_hash_8 - current[8];
    current[9] <== current[8] + should_process_8 * diff_process_8;

    // Level 9: process only if level < tree_depth
    component lt_9 = LessThan(32);
    lt_9.in[0] <== 9;
    lt_9.in[1] <== tree_depth;
    signal should_process_9;
    should_process_9 <== lt_9.out;
    component hash_right_9 = Poseidon2Hash2();
    hash_right_9.in[0] <== proof[9];
    hash_right_9.in[1] <== current[9];
    component hash_left_9 = Poseidon2Hash2();
    hash_left_9.in[0] <== current[9];
    hash_left_9.in[1] <== proof[9];
    component sibling_zero_9 = IsZero();
    sibling_zero_9.in <== proof[9];
    signal sibling_not_zero_9;
    sibling_not_zero_9 <== 1 - sibling_zero_9.out;
    signal diff_left_9;
    diff_left_9 <== hash_left_9.out - current[9];
    signal left_case_9;
    left_case_9 <== current[9] + sibling_not_zero_9 * diff_left_9;
    signal diff_right_9;
    diff_right_9 <== hash_right_9.out - left_case_9;
    signal sel_hash_9;
    sel_hash_9 <== left_case_9 + n2b.out[9] * diff_right_9;
    signal diff_process_9;
    diff_process_9 <== sel_hash_9 - current[9];
    current[10] <== current[9] + should_process_9 * diff_process_9;

    // Level 10: process only if level < tree_depth
    component lt_10 = LessThan(32);
    lt_10.in[0] <== 10;
    lt_10.in[1] <== tree_depth;
    signal should_process_10;
    should_process_10 <== lt_10.out;
    component hash_right_10 = Poseidon2Hash2();
    hash_right_10.in[0] <== proof[10];
    hash_right_10.in[1] <== current[10];
    component hash_left_10 = Poseidon2Hash2();
    hash_left_10.in[0] <== current[10];
    hash_left_10.in[1] <== proof[10];
    component sibling_zero_10 = IsZero();
    sibling_zero_10.in <== proof[10];
    signal sibling_not_zero_10;
    sibling_not_zero_10 <== 1 - sibling_zero_10.out;
    signal diff_left_10;
    diff_left_10 <== hash_left_10.out - current[10];
    signal left_case_10;
    left_case_10 <== current[10] + sibling_not_zero_10 * diff_left_10;
    signal diff_right_10;
    diff_right_10 <== hash_right_10.out - left_case_10;
    signal sel_hash_10;
    sel_hash_10 <== left_case_10 + n2b.out[10] * diff_right_10;
    signal diff_process_10;
    diff_process_10 <== sel_hash_10 - current[10];
    current[11] <== current[10] + should_process_10 * diff_process_10;

    // Level 11: process only if level < tree_depth
    component lt_11 = LessThan(32);
    lt_11.in[0] <== 11;
    lt_11.in[1] <== tree_depth;
    signal should_process_11;
    should_process_11 <== lt_11.out;
    component hash_right_11 = Poseidon2Hash2();
    hash_right_11.in[0] <== proof[11];
    hash_right_11.in[1] <== current[11];
    component hash_left_11 = Poseidon2Hash2();
    hash_left_11.in[0] <== current[11];
    hash_left_11.in[1] <== proof[11];
    component sibling_zero_11 = IsZero();
    sibling_zero_11.in <== proof[11];
    signal sibling_not_zero_11;
    sibling_not_zero_11 <== 1 - sibling_zero_11.out;
    signal diff_left_11;
    diff_left_11 <== hash_left_11.out - current[11];
    signal left_case_11;
    left_case_11 <== current[11] + sibling_not_zero_11 * diff_left_11;
    signal diff_right_11;
    diff_right_11 <== hash_right_11.out - left_case_11;
    signal sel_hash_11;
    sel_hash_11 <== left_case_11 + n2b.out[11] * diff_right_11;
    signal diff_process_11;
    diff_process_11 <== sel_hash_11 - current[11];
    current[12] <== current[11] + should_process_11 * diff_process_11;

    // Level 12: process only if level < tree_depth
    component lt_12 = LessThan(32);
    lt_12.in[0] <== 12;
    lt_12.in[1] <== tree_depth;
    signal should_process_12;
    should_process_12 <== lt_12.out;
    component hash_right_12 = Poseidon2Hash2();
    hash_right_12.in[0] <== proof[12];
    hash_right_12.in[1] <== current[12];
    component hash_left_12 = Poseidon2Hash2();
    hash_left_12.in[0] <== current[12];
    hash_left_12.in[1] <== proof[12];
    component sibling_zero_12 = IsZero();
    sibling_zero_12.in <== proof[12];
    signal sibling_not_zero_12;
    sibling_not_zero_12 <== 1 - sibling_zero_12.out;
    signal diff_left_12;
    diff_left_12 <== hash_left_12.out - current[12];
    signal left_case_12;
    left_case_12 <== current[12] + sibling_not_zero_12 * diff_left_12;
    signal diff_right_12;
    diff_right_12 <== hash_right_12.out - left_case_12;
    signal sel_hash_12;
    sel_hash_12 <== left_case_12 + n2b.out[12] * diff_right_12;
    signal diff_process_12;
    diff_process_12 <== sel_hash_12 - current[12];
    current[13] <== current[12] + should_process_12 * diff_process_12;

    // Level 13: process only if level < tree_depth
    component lt_13 = LessThan(32);
    lt_13.in[0] <== 13;
    lt_13.in[1] <== tree_depth;
    signal should_process_13;
    should_process_13 <== lt_13.out;
    component hash_right_13 = Poseidon2Hash2();
    hash_right_13.in[0] <== proof[13];
    hash_right_13.in[1] <== current[13];
    component hash_left_13 = Poseidon2Hash2();
    hash_left_13.in[0] <== current[13];
    hash_left_13.in[1] <== proof[13];
    component sibling_zero_13 = IsZero();
    sibling_zero_13.in <== proof[13];
    signal sibling_not_zero_13;
    sibling_not_zero_13 <== 1 - sibling_zero_13.out;
    signal diff_left_13;
    diff_left_13 <== hash_left_13.out - current[13];
    signal left_case_13;
    left_case_13 <== current[13] + sibling_not_zero_13 * diff_left_13;
    signal diff_right_13;
    diff_right_13 <== hash_right_13.out - left_case_13;
    signal sel_hash_13;
    sel_hash_13 <== left_case_13 + n2b.out[13] * diff_right_13;
    signal diff_process_13;
    diff_process_13 <== sel_hash_13 - current[13];
    current[14] <== current[13] + should_process_13 * diff_process_13;

    // Level 14: process only if level < tree_depth
    component lt_14 = LessThan(32);
    lt_14.in[0] <== 14;
    lt_14.in[1] <== tree_depth;
    signal should_process_14;
    should_process_14 <== lt_14.out;
    component hash_right_14 = Poseidon2Hash2();
    hash_right_14.in[0] <== proof[14];
    hash_right_14.in[1] <== current[14];
    component hash_left_14 = Poseidon2Hash2();
    hash_left_14.in[0] <== current[14];
    hash_left_14.in[1] <== proof[14];
    component sibling_zero_14 = IsZero();
    sibling_zero_14.in <== proof[14];
    signal sibling_not_zero_14;
    sibling_not_zero_14 <== 1 - sibling_zero_14.out;
    signal diff_left_14;
    diff_left_14 <== hash_left_14.out - current[14];
    signal left_case_14;
    left_case_14 <== current[14] + sibling_not_zero_14 * diff_left_14;
    signal diff_right_14;
    diff_right_14 <== hash_right_14.out - left_case_14;
    signal sel_hash_14;
    sel_hash_14 <== left_case_14 + n2b.out[14] * diff_right_14;
    signal diff_process_14;
    diff_process_14 <== sel_hash_14 - current[14];
    current[15] <== current[14] + should_process_14 * diff_process_14;

    // Level 15: process only if level < tree_depth
    component lt_15 = LessThan(32);
    lt_15.in[0] <== 15;
    lt_15.in[1] <== tree_depth;
    signal should_process_15;
    should_process_15 <== lt_15.out;
    component hash_right_15 = Poseidon2Hash2();
    hash_right_15.in[0] <== proof[15];
    hash_right_15.in[1] <== current[15];
    component hash_left_15 = Poseidon2Hash2();
    hash_left_15.in[0] <== current[15];
    hash_left_15.in[1] <== proof[15];
    component sibling_zero_15 = IsZero();
    sibling_zero_15.in <== proof[15];
    signal sibling_not_zero_15;
    sibling_not_zero_15 <== 1 - sibling_zero_15.out;
    signal diff_left_15;
    diff_left_15 <== hash_left_15.out - current[15];
    signal left_case_15;
    left_case_15 <== current[15] + sibling_not_zero_15 * diff_left_15;
    signal diff_right_15;
    diff_right_15 <== hash_right_15.out - left_case_15;
    signal sel_hash_15;
    sel_hash_15 <== left_case_15 + n2b.out[15] * diff_right_15;
    signal diff_process_15;
    diff_process_15 <== sel_hash_15 - current[15];
    current[16] <== current[15] + should_process_15 * diff_process_15;

    // Level 16: process only if level < tree_depth
    component lt_16 = LessThan(32);
    lt_16.in[0] <== 16;
    lt_16.in[1] <== tree_depth;
    signal should_process_16;
    should_process_16 <== lt_16.out;
    component hash_right_16 = Poseidon2Hash2();
    hash_right_16.in[0] <== proof[16];
    hash_right_16.in[1] <== current[16];
    component hash_left_16 = Poseidon2Hash2();
    hash_left_16.in[0] <== current[16];
    hash_left_16.in[1] <== proof[16];
    component sibling_zero_16 = IsZero();
    sibling_zero_16.in <== proof[16];
    signal sibling_not_zero_16;
    sibling_not_zero_16 <== 1 - sibling_zero_16.out;
    signal diff_left_16;
    diff_left_16 <== hash_left_16.out - current[16];
    signal left_case_16;
    left_case_16 <== current[16] + sibling_not_zero_16 * diff_left_16;
    signal diff_right_16;
    diff_right_16 <== hash_right_16.out - left_case_16;
    signal sel_hash_16;
    sel_hash_16 <== left_case_16 + n2b.out[16] * diff_right_16;
    signal diff_process_16;
    diff_process_16 <== sel_hash_16 - current[16];
    current[17] <== current[16] + should_process_16 * diff_process_16;

    // Level 17: process only if level < tree_depth
    component lt_17 = LessThan(32);
    lt_17.in[0] <== 17;
    lt_17.in[1] <== tree_depth;
    signal should_process_17;
    should_process_17 <== lt_17.out;
    component hash_right_17 = Poseidon2Hash2();
    hash_right_17.in[0] <== proof[17];
    hash_right_17.in[1] <== current[17];
    component hash_left_17 = Poseidon2Hash2();
    hash_left_17.in[0] <== current[17];
    hash_left_17.in[1] <== proof[17];
    component sibling_zero_17 = IsZero();
    sibling_zero_17.in <== proof[17];
    signal sibling_not_zero_17;
    sibling_not_zero_17 <== 1 - sibling_zero_17.out;
    signal diff_left_17;
    diff_left_17 <== hash_left_17.out - current[17];
    signal left_case_17;
    left_case_17 <== current[17] + sibling_not_zero_17 * diff_left_17;
    signal diff_right_17;
    diff_right_17 <== hash_right_17.out - left_case_17;
    signal sel_hash_17;
    sel_hash_17 <== left_case_17 + n2b.out[17] * diff_right_17;
    signal diff_process_17;
    diff_process_17 <== sel_hash_17 - current[17];
    current[18] <== current[17] + should_process_17 * diff_process_17;

    // Level 18: process only if level < tree_depth
    component lt_18 = LessThan(32);
    lt_18.in[0] <== 18;
    lt_18.in[1] <== tree_depth;
    signal should_process_18;
    should_process_18 <== lt_18.out;
    component hash_right_18 = Poseidon2Hash2();
    hash_right_18.in[0] <== proof[18];
    hash_right_18.in[1] <== current[18];
    component hash_left_18 = Poseidon2Hash2();
    hash_left_18.in[0] <== current[18];
    hash_left_18.in[1] <== proof[18];
    component sibling_zero_18 = IsZero();
    sibling_zero_18.in <== proof[18];
    signal sibling_not_zero_18;
    sibling_not_zero_18 <== 1 - sibling_zero_18.out;
    signal diff_left_18;
    diff_left_18 <== hash_left_18.out - current[18];
    signal left_case_18;
    left_case_18 <== current[18] + sibling_not_zero_18 * diff_left_18;
    signal diff_right_18;
    diff_right_18 <== hash_right_18.out - left_case_18;
    signal sel_hash_18;
    sel_hash_18 <== left_case_18 + n2b.out[18] * diff_right_18;
    signal diff_process_18;
    diff_process_18 <== sel_hash_18 - current[18];
    current[19] <== current[18] + should_process_18 * diff_process_18;

    // Level 19: process only if level < tree_depth
    component lt_19 = LessThan(32);
    lt_19.in[0] <== 19;
    lt_19.in[1] <== tree_depth;
    signal should_process_19;
    should_process_19 <== lt_19.out;
    component hash_right_19 = Poseidon2Hash2();
    hash_right_19.in[0] <== proof[19];
    hash_right_19.in[1] <== current[19];
    component hash_left_19 = Poseidon2Hash2();
    hash_left_19.in[0] <== current[19];
    hash_left_19.in[1] <== proof[19];
    component sibling_zero_19 = IsZero();
    sibling_zero_19.in <== proof[19];
    signal sibling_not_zero_19;
    sibling_not_zero_19 <== 1 - sibling_zero_19.out;
    signal diff_left_19;
    diff_left_19 <== hash_left_19.out - current[19];
    signal left_case_19;
    left_case_19 <== current[19] + sibling_not_zero_19 * diff_left_19;
    signal diff_right_19;
    diff_right_19 <== hash_right_19.out - left_case_19;
    signal sel_hash_19;
    sel_hash_19 <== left_case_19 + n2b.out[19] * diff_right_19;
    signal diff_process_19;
    diff_process_19 <== sel_hash_19 - current[19];
    current[20] <== current[19] + should_process_19 * diff_process_19;

    // Level 20: process only if level < tree_depth
    component lt_20 = LessThan(32);
    lt_20.in[0] <== 20;
    lt_20.in[1] <== tree_depth;
    signal should_process_20;
    should_process_20 <== lt_20.out;
    component hash_right_20 = Poseidon2Hash2();
    hash_right_20.in[0] <== proof[20];
    hash_right_20.in[1] <== current[20];
    component hash_left_20 = Poseidon2Hash2();
    hash_left_20.in[0] <== current[20];
    hash_left_20.in[1] <== proof[20];
    component sibling_zero_20 = IsZero();
    sibling_zero_20.in <== proof[20];
    signal sibling_not_zero_20;
    sibling_not_zero_20 <== 1 - sibling_zero_20.out;
    signal diff_left_20;
    diff_left_20 <== hash_left_20.out - current[20];
    signal left_case_20;
    left_case_20 <== current[20] + sibling_not_zero_20 * diff_left_20;
    signal diff_right_20;
    diff_right_20 <== hash_right_20.out - left_case_20;
    signal sel_hash_20;
    sel_hash_20 <== left_case_20 + n2b.out[20] * diff_right_20;
    signal diff_process_20;
    diff_process_20 <== sel_hash_20 - current[20];
    current[21] <== current[20] + should_process_20 * diff_process_20;

    // Level 21: process only if level < tree_depth
    component lt_21 = LessThan(32);
    lt_21.in[0] <== 21;
    lt_21.in[1] <== tree_depth;
    signal should_process_21;
    should_process_21 <== lt_21.out;
    component hash_right_21 = Poseidon2Hash2();
    hash_right_21.in[0] <== proof[21];
    hash_right_21.in[1] <== current[21];
    component hash_left_21 = Poseidon2Hash2();
    hash_left_21.in[0] <== current[21];
    hash_left_21.in[1] <== proof[21];
    component sibling_zero_21 = IsZero();
    sibling_zero_21.in <== proof[21];
    signal sibling_not_zero_21;
    sibling_not_zero_21 <== 1 - sibling_zero_21.out;
    signal diff_left_21;
    diff_left_21 <== hash_left_21.out - current[21];
    signal left_case_21;
    left_case_21 <== current[21] + sibling_not_zero_21 * diff_left_21;
    signal diff_right_21;
    diff_right_21 <== hash_right_21.out - left_case_21;
    signal sel_hash_21;
    sel_hash_21 <== left_case_21 + n2b.out[21] * diff_right_21;
    signal diff_process_21;
    diff_process_21 <== sel_hash_21 - current[21];
    current[22] <== current[21] + should_process_21 * diff_process_21;

    // Level 22: process only if level < tree_depth
    component lt_22 = LessThan(32);
    lt_22.in[0] <== 22;
    lt_22.in[1] <== tree_depth;
    signal should_process_22;
    should_process_22 <== lt_22.out;
    component hash_right_22 = Poseidon2Hash2();
    hash_right_22.in[0] <== proof[22];
    hash_right_22.in[1] <== current[22];
    component hash_left_22 = Poseidon2Hash2();
    hash_left_22.in[0] <== current[22];
    hash_left_22.in[1] <== proof[22];
    component sibling_zero_22 = IsZero();
    sibling_zero_22.in <== proof[22];
    signal sibling_not_zero_22;
    sibling_not_zero_22 <== 1 - sibling_zero_22.out;
    signal diff_left_22;
    diff_left_22 <== hash_left_22.out - current[22];
    signal left_case_22;
    left_case_22 <== current[22] + sibling_not_zero_22 * diff_left_22;
    signal diff_right_22;
    diff_right_22 <== hash_right_22.out - left_case_22;
    signal sel_hash_22;
    sel_hash_22 <== left_case_22 + n2b.out[22] * diff_right_22;
    signal diff_process_22;
    diff_process_22 <== sel_hash_22 - current[22];
    current[23] <== current[22] + should_process_22 * diff_process_22;

    // Level 23: process only if level < tree_depth
    component lt_23 = LessThan(32);
    lt_23.in[0] <== 23;
    lt_23.in[1] <== tree_depth;
    signal should_process_23;
    should_process_23 <== lt_23.out;
    component hash_right_23 = Poseidon2Hash2();
    hash_right_23.in[0] <== proof[23];
    hash_right_23.in[1] <== current[23];
    component hash_left_23 = Poseidon2Hash2();
    hash_left_23.in[0] <== current[23];
    hash_left_23.in[1] <== proof[23];
    component sibling_zero_23 = IsZero();
    sibling_zero_23.in <== proof[23];
    signal sibling_not_zero_23;
    sibling_not_zero_23 <== 1 - sibling_zero_23.out;
    signal diff_left_23;
    diff_left_23 <== hash_left_23.out - current[23];
    signal left_case_23;
    left_case_23 <== current[23] + sibling_not_zero_23 * diff_left_23;
    signal diff_right_23;
    diff_right_23 <== hash_right_23.out - left_case_23;
    signal sel_hash_23;
    sel_hash_23 <== left_case_23 + n2b.out[23] * diff_right_23;
    signal diff_process_23;
    diff_process_23 <== sel_hash_23 - current[23];
    current[24] <== current[23] + should_process_23 * diff_process_23;

    // Level 24: process only if level < tree_depth
    component lt_24 = LessThan(32);
    lt_24.in[0] <== 24;
    lt_24.in[1] <== tree_depth;
    signal should_process_24;
    should_process_24 <== lt_24.out;
    component hash_right_24 = Poseidon2Hash2();
    hash_right_24.in[0] <== proof[24];
    hash_right_24.in[1] <== current[24];
    component hash_left_24 = Poseidon2Hash2();
    hash_left_24.in[0] <== current[24];
    hash_left_24.in[1] <== proof[24];
    component sibling_zero_24 = IsZero();
    sibling_zero_24.in <== proof[24];
    signal sibling_not_zero_24;
    sibling_not_zero_24 <== 1 - sibling_zero_24.out;
    signal diff_left_24;
    diff_left_24 <== hash_left_24.out - current[24];
    signal left_case_24;
    left_case_24 <== current[24] + sibling_not_zero_24 * diff_left_24;
    signal diff_right_24;
    diff_right_24 <== hash_right_24.out - left_case_24;
    signal sel_hash_24;
    sel_hash_24 <== left_case_24 + n2b.out[24] * diff_right_24;
    signal diff_process_24;
    diff_process_24 <== sel_hash_24 - current[24];
    current[25] <== current[24] + should_process_24 * diff_process_24;

    // Level 25: process only if level < tree_depth
    component lt_25 = LessThan(32);
    lt_25.in[0] <== 25;
    lt_25.in[1] <== tree_depth;
    signal should_process_25;
    should_process_25 <== lt_25.out;
    component hash_right_25 = Poseidon2Hash2();
    hash_right_25.in[0] <== proof[25];
    hash_right_25.in[1] <== current[25];
    component hash_left_25 = Poseidon2Hash2();
    hash_left_25.in[0] <== current[25];
    hash_left_25.in[1] <== proof[25];
    component sibling_zero_25 = IsZero();
    sibling_zero_25.in <== proof[25];
    signal sibling_not_zero_25;
    sibling_not_zero_25 <== 1 - sibling_zero_25.out;
    signal diff_left_25;
    diff_left_25 <== hash_left_25.out - current[25];
    signal left_case_25;
    left_case_25 <== current[25] + sibling_not_zero_25 * diff_left_25;
    signal diff_right_25;
    diff_right_25 <== hash_right_25.out - left_case_25;
    signal sel_hash_25;
    sel_hash_25 <== left_case_25 + n2b.out[25] * diff_right_25;
    signal diff_process_25;
    diff_process_25 <== sel_hash_25 - current[25];
    current[26] <== current[25] + should_process_25 * diff_process_25;

    // Level 26: process only if level < tree_depth
    component lt_26 = LessThan(32);
    lt_26.in[0] <== 26;
    lt_26.in[1] <== tree_depth;
    signal should_process_26;
    should_process_26 <== lt_26.out;
    component hash_right_26 = Poseidon2Hash2();
    hash_right_26.in[0] <== proof[26];
    hash_right_26.in[1] <== current[26];
    component hash_left_26 = Poseidon2Hash2();
    hash_left_26.in[0] <== current[26];
    hash_left_26.in[1] <== proof[26];
    component sibling_zero_26 = IsZero();
    sibling_zero_26.in <== proof[26];
    signal sibling_not_zero_26;
    sibling_not_zero_26 <== 1 - sibling_zero_26.out;
    signal diff_left_26;
    diff_left_26 <== hash_left_26.out - current[26];
    signal left_case_26;
    left_case_26 <== current[26] + sibling_not_zero_26 * diff_left_26;
    signal diff_right_26;
    diff_right_26 <== hash_right_26.out - left_case_26;
    signal sel_hash_26;
    sel_hash_26 <== left_case_26 + n2b.out[26] * diff_right_26;
    signal diff_process_26;
    diff_process_26 <== sel_hash_26 - current[26];
    current[27] <== current[26] + should_process_26 * diff_process_26;

    // Level 27: process only if level < tree_depth
    component lt_27 = LessThan(32);
    lt_27.in[0] <== 27;
    lt_27.in[1] <== tree_depth;
    signal should_process_27;
    should_process_27 <== lt_27.out;
    component hash_right_27 = Poseidon2Hash2();
    hash_right_27.in[0] <== proof[27];
    hash_right_27.in[1] <== current[27];
    component hash_left_27 = Poseidon2Hash2();
    hash_left_27.in[0] <== current[27];
    hash_left_27.in[1] <== proof[27];
    component sibling_zero_27 = IsZero();
    sibling_zero_27.in <== proof[27];
    signal sibling_not_zero_27;
    sibling_not_zero_27 <== 1 - sibling_zero_27.out;
    signal diff_left_27;
    diff_left_27 <== hash_left_27.out - current[27];
    signal left_case_27;
    left_case_27 <== current[27] + sibling_not_zero_27 * diff_left_27;
    signal diff_right_27;
    diff_right_27 <== hash_right_27.out - left_case_27;
    signal sel_hash_27;
    sel_hash_27 <== left_case_27 + n2b.out[27] * diff_right_27;
    signal diff_process_27;
    diff_process_27 <== sel_hash_27 - current[27];
    current[28] <== current[27] + should_process_27 * diff_process_27;

    // Level 28: process only if level < tree_depth
    component lt_28 = LessThan(32);
    lt_28.in[0] <== 28;
    lt_28.in[1] <== tree_depth;
    signal should_process_28;
    should_process_28 <== lt_28.out;
    component hash_right_28 = Poseidon2Hash2();
    hash_right_28.in[0] <== proof[28];
    hash_right_28.in[1] <== current[28];
    component hash_left_28 = Poseidon2Hash2();
    hash_left_28.in[0] <== current[28];
    hash_left_28.in[1] <== proof[28];
    component sibling_zero_28 = IsZero();
    sibling_zero_28.in <== proof[28];
    signal sibling_not_zero_28;
    sibling_not_zero_28 <== 1 - sibling_zero_28.out;
    signal diff_left_28;
    diff_left_28 <== hash_left_28.out - current[28];
    signal left_case_28;
    left_case_28 <== current[28] + sibling_not_zero_28 * diff_left_28;
    signal diff_right_28;
    diff_right_28 <== hash_right_28.out - left_case_28;
    signal sel_hash_28;
    sel_hash_28 <== left_case_28 + n2b.out[28] * diff_right_28;
    signal diff_process_28;
    diff_process_28 <== sel_hash_28 - current[28];
    current[29] <== current[28] + should_process_28 * diff_process_28;

    // Level 29: process only if level < tree_depth
    component lt_29 = LessThan(32);
    lt_29.in[0] <== 29;
    lt_29.in[1] <== tree_depth;
    signal should_process_29;
    should_process_29 <== lt_29.out;
    component hash_right_29 = Poseidon2Hash2();
    hash_right_29.in[0] <== proof[29];
    hash_right_29.in[1] <== current[29];
    component hash_left_29 = Poseidon2Hash2();
    hash_left_29.in[0] <== current[29];
    hash_left_29.in[1] <== proof[29];
    component sibling_zero_29 = IsZero();
    sibling_zero_29.in <== proof[29];
    signal sibling_not_zero_29;
    sibling_not_zero_29 <== 1 - sibling_zero_29.out;
    signal diff_left_29;
    diff_left_29 <== hash_left_29.out - current[29];
    signal left_case_29;
    left_case_29 <== current[29] + sibling_not_zero_29 * diff_left_29;
    signal diff_right_29;
    diff_right_29 <== hash_right_29.out - left_case_29;
    signal sel_hash_29;
    sel_hash_29 <== left_case_29 + n2b.out[29] * diff_right_29;
    signal diff_process_29;
    diff_process_29 <== sel_hash_29 - current[29];
    current[30] <== current[29] + should_process_29 * diff_process_29;

    // Level 30: process only if level < tree_depth
    component lt_30 = LessThan(32);
    lt_30.in[0] <== 30;
    lt_30.in[1] <== tree_depth;
    signal should_process_30;
    should_process_30 <== lt_30.out;
    component hash_right_30 = Poseidon2Hash2();
    hash_right_30.in[0] <== proof[30];
    hash_right_30.in[1] <== current[30];
    component hash_left_30 = Poseidon2Hash2();
    hash_left_30.in[0] <== current[30];
    hash_left_30.in[1] <== proof[30];
    component sibling_zero_30 = IsZero();
    sibling_zero_30.in <== proof[30];
    signal sibling_not_zero_30;
    sibling_not_zero_30 <== 1 - sibling_zero_30.out;
    signal diff_left_30;
    diff_left_30 <== hash_left_30.out - current[30];
    signal left_case_30;
    left_case_30 <== current[30] + sibling_not_zero_30 * diff_left_30;
    signal diff_right_30;
    diff_right_30 <== hash_right_30.out - left_case_30;
    signal sel_hash_30;
    sel_hash_30 <== left_case_30 + n2b.out[30] * diff_right_30;
    signal diff_process_30;
    diff_process_30 <== sel_hash_30 - current[30];
    current[31] <== current[30] + should_process_30 * diff_process_30;

    // Level 31: process only if level < tree_depth
    component lt_31 = LessThan(32);
    lt_31.in[0] <== 31;
    lt_31.in[1] <== tree_depth;
    signal should_process_31;
    should_process_31 <== lt_31.out;
    component hash_right_31 = Poseidon2Hash2();
    hash_right_31.in[0] <== proof[31];
    hash_right_31.in[1] <== current[31];
    component hash_left_31 = Poseidon2Hash2();
    hash_left_31.in[0] <== current[31];
    hash_left_31.in[1] <== proof[31];
    component sibling_zero_31 = IsZero();
    sibling_zero_31.in <== proof[31];
    signal sibling_not_zero_31;
    sibling_not_zero_31 <== 1 - sibling_zero_31.out;
    signal diff_left_31;
    diff_left_31 <== hash_left_31.out - current[31];
    signal left_case_31;
    left_case_31 <== current[31] + sibling_not_zero_31 * diff_left_31;
    signal diff_right_31;
    diff_right_31 <== hash_right_31.out - left_case_31;
    signal sel_hash_31;
    sel_hash_31 <== left_case_31 + n2b.out[31] * diff_right_31;
    signal diff_process_31;
    diff_process_31 <== sel_hash_31 - current[31];
    current[32] <== current[31] + should_process_31 * diff_process_31;

    component root_eq = IsEqual();
    root_eq.in[0] <== current[32];
    root_eq.in[1] <== expected_root;
    root_eq.out === 1;
}
